{"name": "test_login_success", "status": "broken", "statusDetails": {"message": "KeyError: 'object'", "trace": "@pytest.fixture(scope='session',autouse=True)\n    def session_fixture():\n        path=\"/api/auth/login\"\n        data={'username':CommonData.mobile,\n              'password':CommonData.password}\n        resp=http.post(path,data)\n>       CommonData.token=resp['object']['token']\nE       KeyError: 'object'\n\nconftest.py:12: KeyError"}, "start": 1586682379594, "stop": 1586682379594, "uuid": "b2499b05-7bd5-43e4-b167-1a098c1422f4", "historyId": "685c921f5afb3e7bfbb279594c0c880f", "testCaseId": "e431e77f7db472898168a47cdea25f27", "fullName": "testcases.sys.test_sys_login.Test_login#test_login_success", "labels": [{"name": "story", "value": "登录成功"}, {"name": "parentSuite", "value": "testcases.sys"}, {"name": "suite", "value": "test_sys_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "DESKTOP-RML6UCN"}, {"name": "thread", "value": "24280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.sys.test_sys_login"}]}